### PR TITLE
filter exact matches if YOUTUBE_QUERY starts with double quotes.

### PR DESCRIPTION
**Pull request by keratagpro**
Possible addition to help with #4?

### CODE REVIEW

**Comment by ylambda** [comment]
This is a nice idea. Help me understand the `!query.startsWith('"')` line.

Right now, the YOUTUBE_QUERY is `"TagPro"` with quotes. I think this code would enforce the channel name or status to have `"TagPro"` including the quotes. I think we should strip out the quotes in this check, so only `TagPro` would be required.

In addition, I think we should include the channel description in the search. Also possibly case-insensitive.

What do you think?

**Comment by keratagpro** [comment]
You're right, the second part of `filterExactMatches` should strip the double quotes and make a case-insensitive search. I'll add that in.

**Comment by keratagpro** [comment]
I didn't want to reinvent the wheel, so I added `lodash.trim` as a dependency.

**Comment by ylambda** [comment]
Excellent, this looks great.

:+1:

**Pull request merged**
